DefaultTerms: []
PropertyMappings:
  - InternalCode: '3bc66bb8-4679-45ed-bb8d-ab1b1cf4bb1a'
    Name: 'LinkNulledBusinessKeyBehaviour - Project'
    EntityTypeId: '012e1a4a-79e5-4d97-85c5-6747a0a34c42'
    PropertyId: '2b41de3f-a477-4ff9-ba4f-e4b3119f6351'
